### ISSUE TITLE
Not published to npm

### ISSUE THREAD

**Issue by jmheik** [sparkbox/passport-harvest#1]
Readme instructs to install this module with npm but it is not available there.

**Comment by joeycozza** [comment]
come on sparkbox, should would be nice to have this published on npm...

**Comment by cromwellryan** [comment]
Hey @jmheik and @joeycozza!  We’re so excited you found this strategy, but to be completely honest, we don’t use this at all any longer.  We wouldn’t feel comfortable publishing to npmjs.com and setting an expectation that it’s going to receive active support going forward.  Just doesn't seem right.

That said, `npm` does natively support [Github Urls in `dependencies`](https://docs.npmjs.com/files/package.json#github-urls). Hopefully that works well enough.  I've created a [Release Tag](https://github.com/sparkbox/passport-harvest/releases/tag/v0.1.0) for you to specify in case changes do occur in the future.

We'll also update the [README](https://github.com/sparkbox/passport-harvest/blob/v0.1.0/README.md) to mention that this repo/module is no longer actively supported by our team directly.

**Comment by bryanbraun** [comment]
With the README updated, I'm going to go ahead and close this issue. :+1:
